### ISSUE TITLE
Change the thank you msg after submitting form

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Ranger-Site#10]
Below the text that is there now please add:
לרכישה אונליין לחץ כאן והזן את קוד הקופון RNG100 המקנה הנחה של 30%.
https://www.berghoff.co.il/mafuach-meavrer-le-mangal-763.html
Hebrew is flipped, please take from the whatsapp

**Comment by MeanEYE** [comment]
Did. Question is whether just shove link or not.

**Comment by hanan-avzuk** [comment]
We need to change 2 things cause Eli sucks :

1. Discount is 35% and not 30%
2. The link should say : לרכישה לחצו כאן

**Comment by MeanEYE** [comment]
Eventually. I can't be switching projects willy nilly because he felt the need to change it again but forgot last time which was 15 minutes ago.

**Comment by MeanEYE** [comment]
@talovdat is this still current?

**Comment by talovdat** [comment]
No.
