### ISSUE TITLE
List numbers don't have dots at the end.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Ranger-Site#2]
![image](https://user-images.githubusercontent.com/1911594/27769785-1a1739ac-5f32-11e7-9dd6-d9c99bbbe1cf.png)
Numbers are most likely generated by CSS counter. @iliyaM can fill in on more details.

**Comment by VladimirWebDev** [comment]
Consulted with @iliyaM. Dots added and changed width of OL so that all text is in one line.

**Comment by MeanEYE** [comment]
Good.
