### ISSUE TITLE
Site doesn't pass W3C validation.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Ranger-Site#3]
[As seen here](https://validator.w3.org/nu/?doc=http%3A%2F%2Flp.berghoff.co.il%2F) site doesn't pass validation. Notable issues are using `li` elements as direct children of `div`.

@iliyaM you just make sure this passes afterwards. @VladimirWebDev this bug is solely yours. What you can't do, write here.

**Comment by VladimirWebDev** [comment]
Errors for LI elements fixed.

Error: Attribute seamless not allowed on element iframe at this point.
Spoke with @MeanEYE about this. It should be done on system level.
