### ISSUE TITLE
Optimize mobile images.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Ranger-Site#4]
![image](https://user-images.githubusercontent.com/1911594/27769843-57b63da2-5f33-11e7-8ca9-247f7ffc97ac.png)

PageSpeed Insights complain about two header images being too big. These two files need to be optimized with Guetzli tool. If you don't have it let me know and I'll provide it.

**Comment by VladimirWebDev** [comment]
Optimized with guetzli. Tested with Page Speed Insights with url generated with ngrok since local can't be tested as I figure out. Got 100/100.

**Comment by MeanEYE** [comment]
Good! You can't test "localhost" as it's defined locally. Ngrok however works. I'll redeploy tomorrow.
